spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
          url: jdbc:clickhouse://192.168.110.61:8123/default
          username: default
          password: 123456
server:
  port: 9494
  shutdown: graceful
logging:
  level:
    root: info
    com.lzp: debug