# === spring config ===
spring:
  main:
    allow-bean-definition-overriding: false
    allow-circular-references: true
  application:
    name: @project.artifactId@
  profiles:
    active: dubbo
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1024MB
